### ISSUE TITLE
'Folio' operations works slow

### ISSUE THREAD

**Issue by Tardo** [hootel/hootel#2]
When operations are performed such as checkin in "folios" with many reserves... the process take too time to complete.

The main problem are write calls... these calls launch longpolling connections and this take too time to complete.

**Comment by DarioLodeiros** [comment]
The problem is 
https://github.com/dockdoo/hootel/blob/70dd16ada0167e16fe50e4fb5b7b0a4131f3d4c3/hotel_calendar/static/src/js/hcalendar.js#L1442
That reload all reservations in calendar
