### ISSUE TITLE
Calendar fail when exists a real room without vroom assigned

### ISSUE THREAD

**Issue by Tardo** [hootel/hootel#20]
On calendar load raise an exception...
```
Uncaught TypeError: Cannot use 'in' operator to search for '01/04/2018' in undefined
```

**Comment by Tardo** [comment]
@pabloqb can you explain how reproduce this bug? I have a room without vroom assigned and can load calendar without problems....

**Comment by pabloqb** [comment]
Create two virtual rooms. Add the same real room to both virtual rooms. 

Edit the real room and assign the second virtual room in the Price Virtual Room field.

Delete the second virtual room. You can remove the real room first or delete the virtual room directly.

If you go to the real room cofiguration you can see that it has assigned no virtual room. If you reaload the calendar you should get the error message,
