### ISSUE TITLE
Segmentation problem

### ISSUE THREAD

**Issue by OsoTranquilo** [hootel/hootel#41]
If you add a checkin to a file after having checked a person, that person does not have the new segmentation attached if you access their client file. However, if you check it again on the same tab, it shows you the complete segmentation of the file.

Example:

1. Checkin 'Pepito Perez' with segmentation Leisure / Travel Solo.
2. The Card is segmented as Leisure / Travel Solo.
3. Edit the Card and in the room add another segmentation, for example, Leisure / Student.
4.- Access to the client file.- You only have Leisure / Travel Solo, despite having a checkin in a file in which we have added / updated the segmentation.

**Comment by Tardo** [comment]
What is the status of this issue?

**Comment by OsoTranquilo** [comment]
It is not fixed
