### ISSUE TITLE
Move modules to 11.0

### ISSUE THREAD

**Issue by pabloqb** [hootel/hootel#49]
Update modules to run the 11.0 

- Move python code from 2 to 3
- Remove deprecated code in Odoo 11.0
- Fix errors in views

This task should be divided by tasks

- [x] Hotel Management | hotel
- [ ] Hotel Calendar | hotel_calendar 
- [ ] Hotel Calendar WuBook | hotel_calendar_wubook
- [ ] Hotel MyDataBI Exporter | hotel_data_bi 
- [ ] Hotel l10n_es | hotel_l10n_es 
- [ ] Hotel Revenue Exporter | hotel_revenue 
- [ ] Hotel WuBook | hotel_wubook 
- [ ] Hotel WuBook Prototype | hotel_wubook_proto

**Comment by Tardo** [comment]
Hotel installable... ~~but settings page doesn't work... need be updated.~~

Changes made:
- Disabled xml records with 'key2' = 'tree_but_open'
- ir.values xml records that sets default values changed to ir.default
- ir.values xml records that add option to "Actions" menu removed and update linked action to new mode.
- ir.cron xml records changed to new mode.
- Update ```<openerp><data>``` to new mode: ```<odoo>```
- Improved "tree" views... now parser is more strict
- Other stuff
