### ISSUE TITLE
Improve checkin usability at create / modify clients

### ISSUE THREAD

**Issue by pabloqb** [hootel/hootel#8]
By doing a checkin is quite easy create a new customer by accident just modifying the name or last name in the checkin wizard. Improve the usability: modify the current client by default and use a 'button' for indicating a new one. 

Use a search box for searching the existing users but do not allow create them. The user must use the button to clearly indicate that a new client is comming.

**Comment by DarioLodeiros** [comment]
We must add folio field "tags", and add it in checkin process, and in a new Checkin, if the folio yet has a tags, we add by default this tags...
